annotations:
  catalog.cattle.io/certified: partner
  catalog.cattle.io/display-name: Apache Cassandra
  catalog.cattle.io/kube-version: '>=1.19-0'
  catalog.cattle.io/release-name: cassandra
  category: Database
  images: |
    - name: cassandra-exporter
      image: docker.io/bitnami/cassandra-exporter:2.3.8-debian-11-r394
    - name: cassandra
      image: docker.io/bitnami/cassandra:4.1.3-debian-11-r37
    - name: os-shell
      image: docker.io/bitnami/os-shell:11-debian-11-r54
  licenses: Apache-2.0
apiVersion: v2
appVersion: 4.1.3
dependencies:
- name: common
  repository: file://./charts/common
  tags:
  - bitnami-common
  version: 2.x.x
description: Apache Cassandra is an open source distributed database management system
  designed to handle large amounts of data across many servers, providing high availability
  with no single point of failure.
home: https://bitnami.com
icon: https://svn.apache.org/repos/asf/comdev/project-logos/originals/cassandra-4.svg
keywords:
- cassandra
- database
- nosql
maintainers:
- name: VMware, Inc.
  url: https://github.com/bitnami/charts
name: cassandra
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/cassandra
version: 10.5.3
