annotations:
  catalog.cattle.io/certified: partner
  catalog.cattle.io/display-name: MariaDB
  catalog.cattle.io/kube-version: '>=1.19-0'
  catalog.cattle.io/release-name: mariadb
  category: Database
  images: |
    - name: mariadb
      image: docker.io/bitnami/mariadb:11.0.3-debian-11-r5
    - name: mysqld-exporter
      image: docker.io/bitnami/mysqld-exporter:0.15.0-debian-11-r24
    - name: os-shell
      image: docker.io/bitnami/os-shell:11-debian-11-r43
  licenses: Apache-2.0
apiVersion: v2
appVersion: 11.0.3
dependencies:
- name: common
  repository: file://./charts/common
  tags:
  - bitnami-common
  version: 2.x.x
description: MariaDB is an open source, community-developed SQL database server that
  is widely in use around the world due to its enterprise features, flexibility, and
  collaboration with leading tech firms.
home: https://bitnami.com
icon: https://mariadb.com/wp-content/uploads/2019/11/mariadb-logo-vert_black-transparent.png
keywords:
- mariadb
- mysql
- database
- sql
- prometheus
maintainers:
- name: VMware, Inc.
  url: https://github.com/bitnami/charts
name: mariadb
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/mariadb
version: 13.1.3
